// <auto-generated />
using System;
using Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(WoorkNeedlesContext))]
    partial class WoorkNeedlesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infraestructure.Persistence.Models.CategoriaInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("CategoriaInsumo_pkey");

                    b.HasIndex(new[] { "Nombre" }, "CategoriaInsumo_nombre_key")
                        .IsUnique();

                    b.ToTable("CategoriaInsumo", (string)null);
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("CategoriaProducto_pkey");

                    b.HasIndex(new[] { "Nombre" }, "CategoriaProducto_nombre_key")
                        .IsUnique();

                    b.ToTable("CategoriaProducto", (string)null);
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Ciudade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Iddepart")
                        .HasColumnType("integer")
                        .HasColumnName("iddepart");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("Ciudades_pkey");

                    b.HasIndex("Iddepart");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Fechamodificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechamodificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Idciudad")
                        .HasColumnType("integer")
                        .HasColumnName("idciudad");

                    b.Property<int>("Iddepart")
                        .HasColumnType("integer")
                        .HasColumnName("iddepart");

                    b.Property<int>("Idpais")
                        .HasColumnType("integer")
                        .HasColumnName("idpais");

                    b.Property<string>("Nombres")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombres");

                    b.Property<string>("PreferenciasCompra")
                        .HasColumnType("text")
                        .HasColumnName("preferencias_compra");

                    b.Property<string>("Razonsocial")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razonsocial");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("Tipocliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipocliente");

                    b.Property<string>("Tipodocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipodocumento");

                    b.HasKey("Id")
                        .HasName("clientes_pkey");

                    b.HasIndex("Idciudad");

                    b.HasIndex("Iddepart");

                    b.HasIndex("Idpais");

                    b.HasIndex(new[] { "Documento" }, "clientes_documento_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "clientes_email_key")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Colore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigohex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigohex");

                    b.Property<DateTime>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Fechamodificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechamodificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("Colores_pkey");

                    b.ToTable("Colores");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Idpais")
                        .HasColumnType("integer")
                        .HasColumnName("idpais");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("Departamentos_pkey");

                    b.HasIndex("Idpais");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int?>("Idinventario")
                        .HasColumnType("integer")
                        .HasColumnName("idinventario");

                    b.Property<int>("Idpedido")
                        .HasColumnType("integer")
                        .HasColumnName("idpedido");

                    b.Property<int>("Idproducto")
                        .HasColumnType("integer")
                        .HasColumnName("idproducto");

                    b.Property<decimal>("Preciounitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preciounitario");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id")
                        .HasName("DetallePedidos_pkey");

                    b.HasIndex("Idinventario");

                    b.HasIndex("Idpedido");

                    b.HasIndex("Idproducto");

                    b.ToTable("DetallePedidos");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Devolucione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<int?>("Idcliente")
                        .HasColumnType("integer")
                        .HasColumnName("idcliente");

                    b.Property<int>("Idpedido")
                        .HasColumnType("integer")
                        .HasColumnName("idpedido");

                    b.Property<int>("Idusuario")
                        .HasColumnType("integer")
                        .HasColumnName("idusuario");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.HasKey("Id")
                        .HasName("Devoluciones_pkey");

                    b.HasIndex("Idcliente");

                    b.HasIndex("Idpedido");

                    b.HasIndex("Idusuario");

                    b.ToTable("Devoluciones");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.HistorialPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estadoactual")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estadoactual");

                    b.Property<string>("Estadoanterior")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estadoanterior");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("Idpedido")
                        .HasColumnType("integer")
                        .HasColumnName("idpedido");

                    b.Property<int>("Idusuario")
                        .HasColumnType("integer")
                        .HasColumnName("idusuario");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.HasKey("Id")
                        .HasName("HistorialPedidos_pkey");

                    b.HasIndex("Idpedido");

                    b.HasIndex("Idusuario");

                    b.ToTable("HistorialPedidos");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Fechamodificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechamodificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Idcategoria")
                        .HasColumnType("integer")
                        .HasColumnName("idcategoria");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("proveedor");

                    b.Property<decimal>("Stockactual")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("stockactual");

                    b.Property<decimal>("Stockalerta")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("stockalerta");

                    b.Property<string>("Unidadmedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidadmedida");

                    b.HasKey("Id")
                        .HasName("Insumos_pkey");

                    b.HasIndex("Idcategoria");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.InsumosProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cantidad");

                    b.Property<int>("Idinsumo")
                        .HasColumnType("integer")
                        .HasColumnName("idinsumo");

                    b.Property<int>("Idproducto")
                        .HasColumnType("integer")
                        .HasColumnName("idproducto");

                    b.HasKey("Id")
                        .HasName("InsumosProducto_pkey");

                    b.HasIndex("Idinsumo");

                    b.HasIndex(new[] { "Idproducto", "Idinsumo" }, "InsumosProducto_idproducto_idinsumo_key")
                        .IsUnique();

                    b.ToTable("InsumosProducto", (string)null);
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("Fechamodificacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechamodificacion");

                    b.Property<int?>("Idcolor")
                        .HasColumnType("integer")
                        .HasColumnName("idcolor");

                    b.Property<int?>("Idproducto")
                        .HasColumnType("integer")
                        .HasColumnName("idproducto");

                    b.Property<int?>("Idtalla")
                        .HasColumnType("integer")
                        .HasColumnName("idtalla");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock");

                    b.HasKey("Id")
                        .HasName("Inventario_pkey");

                    b.HasIndex("Idcolor");

                    b.HasIndex("Idtalla");

                    b.HasIndex(new[] { "Idproducto", "Idcolor", "Idtalla" }, "Inventario_idproducto_idcolor_idtalla_key")
                        .IsUnique();

                    b.ToTable("Inventario", (string)null);
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'completado'::character varying");

                    b.Property<DateTime?>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Fechapago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechapago")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Idpedido")
                        .HasColumnType("integer")
                        .HasColumnName("idpedido");

                    b.Property<int>("Idusuario")
                        .HasColumnType("integer")
                        .HasColumnName("idusuario");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia");

                    b.Property<string>("Tipopago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipopago");

                    b.HasKey("Id")
                        .HasName("Pagos_pkey");

                    b.HasIndex("Idpedido");

                    b.HasIndex("Idusuario");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Paise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("codigo");

                    b.Property<DateTime?>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("Paises_pkey");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Descuento")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("descuento")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Direccionentrega")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccionentrega");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'pendiente'::character varying");

                    b.Property<DateTime?>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Fechaentrega")
                        .HasColumnType("date")
                        .HasColumnName("fechaentrega");

                    b.Property<DateTime?>("Fechamodificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechamodificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Fechapedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechapedido")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Fechentregaaprox")
                        .HasColumnType("date")
                        .HasColumnName("fechentregaaprox");

                    b.Property<int>("Idcliente")
                        .HasColumnType("integer")
                        .HasColumnName("idcliente");

                    b.Property<int>("Idusuario")
                        .HasColumnType("integer")
                        .HasColumnName("idusuario");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("Pedidos_pkey");

                    b.HasIndex("Idcliente");

                    b.HasIndex("Idusuario");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Fechamodificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechamodificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Genero")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("genero");

                    b.Property<int>("Idcategoria")
                        .HasColumnType("integer")
                        .HasColumnName("idcategoria");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Preciobase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preciobase");

                    b.Property<string>("Urlimagen")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("urlimagen");

                    b.HasKey("Id")
                        .HasName("Producto_pkey");

                    b.HasIndex("Idcategoria");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.ProductoColore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Fechamodificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechamodificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Idcolor")
                        .HasColumnType("integer")
                        .HasColumnName("idcolor");

                    b.Property<int?>("Idproducto")
                        .HasColumnType("integer")
                        .HasColumnName("idproducto");

                    b.HasKey("Id")
                        .HasName("ProductoColores_pkey");

                    b.HasIndex("Idcolor");

                    b.HasIndex("Idproducto");

                    b.ToTable("ProductoColores");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.ProductoTalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Fechamodificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechamodificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Idproducto")
                        .HasColumnType("integer")
                        .HasColumnName("idproducto");

                    b.Property<int?>("Idtalla")
                        .HasColumnType("integer")
                        .HasColumnName("idtalla");

                    b.HasKey("Id")
                        .HasName("ProductoTallas_pkey");

                    b.HasIndex("Idproducto");

                    b.HasIndex("Idtalla");

                    b.ToTable("ProductoTallas");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<string>("Permisos")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("permisos")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Id")
                        .HasName("Roles_pkey");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Talla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Fechamodificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechamodificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("Tallas_pkey");

                    b.ToTable("Tallas");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("Fechacreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Fechamodificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechamodificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Idciudad")
                        .HasColumnType("integer")
                        .HasColumnName("idciudad");

                    b.Property<int>("Idpais")
                        .HasColumnType("integer")
                        .HasColumnName("idpais");

                    b.Property<int>("Idrol")
                        .HasColumnType("integer")
                        .HasColumnName("idrol");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("Usuario_pkey");

                    b.HasIndex("Idciudad");

                    b.HasIndex("Idpais");

                    b.HasIndex("Idrol");

                    b.HasIndex(new[] { "Email" }, "Usuario_email_key")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Ciudade", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.Departamento", "IddepartNavigation")
                        .WithMany("Ciudades")
                        .HasForeignKey("Iddepart")
                        .IsRequired()
                        .HasConstraintName("fk_ciudades_depart");

                    b.Navigation("IddepartNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Cliente", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.Ciudade", "IdciudadNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("Idciudad")
                        .IsRequired()
                        .HasConstraintName("fk_cliente_ciudad");

                    b.HasOne("Infraestructure.Persistence.Models.Departamento", "IddepartNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("Iddepart")
                        .IsRequired()
                        .HasConstraintName("fk_cliente_depart");

                    b.HasOne("Infraestructure.Persistence.Models.Paise", "IdpaisNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("Idpais")
                        .IsRequired()
                        .HasConstraintName("fk_cliente_paises");

                    b.Navigation("IdciudadNavigation");

                    b.Navigation("IddepartNavigation");

                    b.Navigation("IdpaisNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Departamento", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.Paise", "IdpaisNavigation")
                        .WithMany("Departamentos")
                        .HasForeignKey("Idpais")
                        .IsRequired()
                        .HasConstraintName("fk_depart_paises");

                    b.Navigation("IdpaisNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.DetallePedido", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.Inventario", "IdinventarioNavigation")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("Idinventario")
                        .HasConstraintName("DetallePedidos_idinventario_fkey");

                    b.HasOne("Infraestructure.Persistence.Models.Pedido", "IdpedidoNavigation")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("Idpedido")
                        .IsRequired()
                        .HasConstraintName("fk_detallep_pedido");

                    b.HasOne("Infraestructure.Persistence.Models.Producto", "IdproductoNavigation")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("Idproducto")
                        .IsRequired()
                        .HasConstraintName("fk_detallep_producto");

                    b.Navigation("IdinventarioNavigation");

                    b.Navigation("IdpedidoNavigation");

                    b.Navigation("IdproductoNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Devolucione", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.Cliente", "IdclienteNavigation")
                        .WithMany("Devoluciones")
                        .HasForeignKey("Idcliente")
                        .HasConstraintName("Devoluciones_idcliente_fkey");

                    b.HasOne("Infraestructure.Persistence.Models.Pedido", "IdpedidoNavigation")
                        .WithMany("Devoluciones")
                        .HasForeignKey("Idpedido")
                        .IsRequired()
                        .HasConstraintName("fk_devoluciones_pedido");

                    b.HasOne("Infraestructure.Persistence.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Devoluciones")
                        .HasForeignKey("Idusuario")
                        .IsRequired()
                        .HasConstraintName("fk_devoluciones_usuario");

                    b.Navigation("IdclienteNavigation");

                    b.Navigation("IdpedidoNavigation");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.HistorialPedido", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.Pedido", "IdpedidoNavigation")
                        .WithMany("HistorialPedidos")
                        .HasForeignKey("Idpedido")
                        .IsRequired()
                        .HasConstraintName("fk_historialp_pedido");

                    b.HasOne("Infraestructure.Persistence.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("HistorialPedidos")
                        .HasForeignKey("Idusuario")
                        .IsRequired()
                        .HasConstraintName("fk_historialp_usuario");

                    b.Navigation("IdpedidoNavigation");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Insumo", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.CategoriaInsumo", "IdcategoriaNavigation")
                        .WithMany("Insumos")
                        .HasForeignKey("Idcategoria")
                        .IsRequired()
                        .HasConstraintName("fk_insumo_categoria");

                    b.Navigation("IdcategoriaNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.InsumosProducto", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.Insumo", "IdinsumoNavigation")
                        .WithMany("InsumosProductos")
                        .HasForeignKey("Idinsumo")
                        .IsRequired()
                        .HasConstraintName("fk_insumosp_insumo");

                    b.HasOne("Infraestructure.Persistence.Models.Producto", "IdproductoNavigation")
                        .WithMany("InsumosProductos")
                        .HasForeignKey("Idproducto")
                        .IsRequired()
                        .HasConstraintName("fk_insumosp_producto");

                    b.Navigation("IdinsumoNavigation");

                    b.Navigation("IdproductoNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Inventario", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.Colore", "IdcolorNavigation")
                        .WithMany("Inventarios")
                        .HasForeignKey("Idcolor")
                        .HasConstraintName("Inventario_idcolor_fkey");

                    b.HasOne("Infraestructure.Persistence.Models.Producto", "IdproductoNavigation")
                        .WithMany("Inventarios")
                        .HasForeignKey("Idproducto")
                        .HasConstraintName("Inventario_idproducto_fkey");

                    b.HasOne("Infraestructure.Persistence.Models.Talla", "IdtallaNavigation")
                        .WithMany("Inventarios")
                        .HasForeignKey("Idtalla")
                        .HasConstraintName("Inventario_idtalla_fkey");

                    b.Navigation("IdcolorNavigation");

                    b.Navigation("IdproductoNavigation");

                    b.Navigation("IdtallaNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Pago", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.Pedido", "IdpedidoNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("Idpedido")
                        .IsRequired()
                        .HasConstraintName("fk_pagos_pedido");

                    b.HasOne("Infraestructure.Persistence.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("Idusuario")
                        .IsRequired()
                        .HasConstraintName("fk_pagos_usuario");

                    b.Navigation("IdpedidoNavigation");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Pedido", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.Cliente", "IdclienteNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("Idcliente")
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_cliente");

                    b.HasOne("Infraestructure.Persistence.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("Idusuario")
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_usuario");

                    b.Navigation("IdclienteNavigation");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Producto", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.CategoriaProducto", "IdcategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("Idcategoria")
                        .IsRequired()
                        .HasConstraintName("fk_prodcuto_categoria");

                    b.Navigation("IdcategoriaNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.ProductoColore", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.Colore", "IdcolorNavigation")
                        .WithMany("ProductoColores")
                        .HasForeignKey("Idcolor")
                        .HasConstraintName("ProductoColores_idcolor_fkey");

                    b.HasOne("Infraestructure.Persistence.Models.Producto", "IdproductoNavigation")
                        .WithMany("ProductoColores")
                        .HasForeignKey("Idproducto")
                        .HasConstraintName("ProductoColores_idproducto_fkey");

                    b.Navigation("IdcolorNavigation");

                    b.Navigation("IdproductoNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.ProductoTalla", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.Producto", "IdproductoNavigation")
                        .WithMany("ProductoTallas")
                        .HasForeignKey("Idproducto")
                        .HasConstraintName("ProductoTallas_idproducto_fkey");

                    b.HasOne("Infraestructure.Persistence.Models.Talla", "IdtallaNavigation")
                        .WithMany("ProductoTallas")
                        .HasForeignKey("Idtalla")
                        .HasConstraintName("ProductoTallas_idtalla_fkey");

                    b.Navigation("IdproductoNavigation");

                    b.Navigation("IdtallaNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Usuario", b =>
                {
                    b.HasOne("Infraestructure.Persistence.Models.Ciudade", "IdciudadNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("Idciudad")
                        .IsRequired()
                        .HasConstraintName("fk_usuario_ciudad");

                    b.HasOne("Infraestructure.Persistence.Models.Paise", "IdpaisNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("Idpais")
                        .IsRequired()
                        .HasConstraintName("fk_usuario_pais");

                    b.HasOne("Infraestructure.Persistence.Models.Role", "IdrolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("Idrol")
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol");

                    b.Navigation("IdciudadNavigation");

                    b.Navigation("IdpaisNavigation");

                    b.Navigation("IdrolNavigation");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.CategoriaInsumo", b =>
                {
                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Ciudade", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Cliente", b =>
                {
                    b.Navigation("Devoluciones");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Colore", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("ProductoColores");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Departamento", b =>
                {
                    b.Navigation("Ciudades");

                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Insumo", b =>
                {
                    b.Navigation("InsumosProductos");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Inventario", b =>
                {
                    b.Navigation("DetallePedidos");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Paise", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Departamentos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Pedido", b =>
                {
                    b.Navigation("DetallePedidos");

                    b.Navigation("Devoluciones");

                    b.Navigation("HistorialPedidos");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Producto", b =>
                {
                    b.Navigation("DetallePedidos");

                    b.Navigation("InsumosProductos");

                    b.Navigation("Inventarios");

                    b.Navigation("ProductoColores");

                    b.Navigation("ProductoTallas");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Talla", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("ProductoTallas");
                });

            modelBuilder.Entity("Infraestructure.Persistence.Models.Usuario", b =>
                {
                    b.Navigation("Devoluciones");

                    b.Navigation("HistorialPedidos");

                    b.Navigation("Pagos");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
